server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dyeing_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  config:
    classpath:log4j2.xml
mybatis:
  config-location:
    - classpath:mybatis-config.xml
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:dms/mapper/*.xml
